# Board43 App: Undertale Battle (v3)
#
# Dodge-box prototype: a red downward-triangle "SOUL" moves with the
# four buttons while a short melody loops on the piezo. Song data is
# pre-compiled to packed bytes by my-apps/songs/build.py; this file
# never parses note names at runtime.
#
#   SW3: Left
#   SW4: Up
#   SW5: Down
#   SW6: Right
#
# Features: Switches (GPIO) + WS2812 16x16 matrix + Buzzer (PWM)

require 'ws2812-plus'
require 'gpio'
require 'pwm'

# ================================================================
# MusicPlayer — byte-decoding monophonic song player
# ================================================================
#
# Song data is a byte String with 4 bytes per event:
#   bytes 0-1: frequency Hz (little-endian, 0 = rest)
#   bytes 2-3: duration ms  (little-endian)
# Articulation gaps between same-pitch repeats are baked in already,
# so #tick does no parsing and no table lookups.
#
#   player = MusicPlayer.new(buzzer, SOME_SONG_DATA)
#   loop do
#     player.tick(TICK_MS)
#     # ... draw your frame ...
#   end
class MusicPlayer
  def initialize(buzzer, data)
    @buzzer    = buzzer
    @bytes     = data.bytes   # one-time string -> int array
    @count     = @bytes.length / 4
    @cursor    = 0
    @remaining = 0
  end

  # Advance playback by elapsed_ms. Common-case cost: one subtract +
  # one compare. Uses a while loop so multiple short events that fit
  # inside a single tick don't get dropped.
  def tick(elapsed_ms)
    @remaining -= elapsed_ms
    while @remaining <= 0
      i = @cursor * 4
      freq = @bytes[i] | (@bytes[i + 1] << 8)
      dur  = @bytes[i + 2] | (@bytes[i + 3] << 8)
      @buzzer.frequency(freq)
      @remaining += dur
      @cursor += 1
      @cursor = 0 if @cursor >= @count
    end
  end

  def stop
    @buzzer.frequency(0)
  end
end

# ================================================================
# Song data — generated by `uv run my-apps/songs/build.py <this-file>`.
# Add another song by dropping `<name>.song` into my-apps/songs/ and
# inserting another `# BEGIN SONG: <name>` / `# END SONG` pair below.
# ================================================================
# BEGIN SONG: megalovania_saw
# 113 notes -> 121 events, 484 bytes
MEGALOVANIA_SAW_DATA = \
  "\x26\x01\x73\x00\x00\x00\x0a\x00\x26\x01\x7d\x00\x4b\x02\x7d\x00\x00\x00\x7d\x00\xb8\x01\x7d\x00\x00\x00\xfa\x00\x9f\x01\x7d\x00" \
  "\x00\x00\x7d\x00\x88\x01\x7d\x00\x00\x00\x7d\x00\x5d\x01\xfa\x00\x26\x01\x7d\x00\x5d\x01\x7d\x00\x88\x01\x7d\x00\x06\x01\x73\x00" \
  "\x00\x00\x0a\x00\x06\x01\x7d\x00\x4b\x02\x7d\x00\x00\x00\x7d\x00\xb8\x01\x7d\x00\x00\x00\xfa\x00\x9f\x01\x7d\x00\x00\x00\x7d\x00" \
  "\x88\x01\x7d\x00\x00\x00\x7d\x00\x5d\x01\xfa\x00\x26\x01\x7d\x00\x5d\x01\x7d\x00\x88\x01\x7d\x00\xf7\x00\x73\x00\x00\x00\x0a\x00" \
  "\xf7\x00\x7d\x00\x4b\x02\x7d\x00\x00\x00\x7d\x00\xb8\x01\x7d\x00\x00\x00\xfa\x00\x9f\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\x7d\x00" \
  "\x00\x00\x7d\x00\x5d\x01\xfa\x00\x26\x01\x7d\x00\x5d\x01\x7d\x00\x88\x01\x7d\x00\xe9\x00\x73\x00\x00\x00\x0a\x00\xe9\x00\x7d\x00" \
  "\x4b\x02\x7d\x00\x00\x00\x7d\x00\xb8\x01\x7d\x00\x00\x00\xfa\x00\x9f\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\x7d\x00\x00\x00\x7d\x00" \
  "\x5d\x01\xfa\x00\x26\x01\x7d\x00\x5d\x01\x7d\x00\x88\x01\x7d\x00\x26\x01\x73\x00\x00\x00\x0a\x00\x26\x01\x7d\x00\x4b\x02\x7d\x00" \
  "\x00\x00\x7d\x00\xb8\x01\x7d\x00\x00\x00\xfa\x00\x9f\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\x7d\x00\x00\x00\x7d\x00\x5d\x01\xfa\x00" \
  "\x26\x01\x7d\x00\x5d\x01\x7d\x00\x88\x01\x7d\x00\x06\x01\x73\x00\x00\x00\x0a\x00\x06\x01\x7d\x00\x4b\x02\x7d\x00\x00\x00\x7d\x00" \
  "\xb8\x01\x7d\x00\x00\x00\xfa\x00\x9f\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\x7d\x00\x00\x00\x7d\x00\x5d\x01\xfa\x00\x26\x01\x7d\x00" \
  "\x5d\x01\x7d\x00\x88\x01\x7d\x00\xf7\x00\x73\x00\x00\x00\x0a\x00\xf7\x00\x7d\x00\x4b\x02\x7d\x00\x00\x00\x7d\x00\xb8\x01\x7d\x00" \
  "\x00\x00\xfa\x00\x9f\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\x7d\x00\x00\x00\x7d\x00\x5d\x01\xfa\x00\x26\x01\x7d\x00\x5d\x01\x7d\x00" \
  "\x88\x01\x7d\x00\xe9\x00\x73\x00\x00\x00\x0a\x00\xe9\x00\x7d\x00\x4b\x02\x7d\x00\x00\x00\x7d\x00\xb8\x01\x7d\x00\x00\x00\xfa\x00" \
  "\x9f\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\x7d\x00\x00\x00\x7d\x00\x5d\x01\xfa\x00\x26\x01\x7d\x00\x5d\x01\x7d\x00\x88\x01\x7d\x00" \
  "\x00\x00\xd0\x07"
# END SONG

# ================================================================
# Hardware
# ================================================================
led       = WS2812.new(pin: Board43::GPIO_LEDOUT, num: 256)
btn_left  = GPIO.new(Board43::GPIO_SW3, GPIO::IN | GPIO::PULL_UP)
btn_up    = GPIO.new(Board43::GPIO_SW4, GPIO::IN | GPIO::PULL_UP)
btn_down  = GPIO.new(Board43::GPIO_SW5, GPIO::IN | GPIO::PULL_UP)
btn_right = GPIO.new(Board43::GPIO_SW6, GPIO::IN | GPIO::PULL_UP)
buzzer    = PWM.new(Board43::GPIO_BUZZER, frequency: 0, duty: 40)

# ================================================================
# Grid / sprite / timing
# ================================================================
GRID_W = 16
GRID_H = 16

# 3x2 "red T" downward triangle — compact, leaves room for attacks.
HEART_SPRITE = ['###', '.#.']
HEART_W = 3
HEART_H = 2
HEART_R = 200
HEART_G = 0
HEART_B = 0

# No sleep: loop cadence is whatever led.show + Ruby work happens to
# be. We use Machine.board_millis to measure real elapsed ms per frame,
# so music and input auto-repeat stay wall-clock correct regardless of
# frame rate.
CONTROL_REPEAT_MS = 96   # step every ~96 ms while a button is held

def draw_heart(led, x, y)
  led.fill(0, 0, 0)
  row = 0
  while row < HEART_H
    bytes = HEART_SPRITE[row].bytes
    col = 0
    while col < HEART_W
      if bytes[col] == 35  # '#'
        led.set_rgb((y + row) * GRID_W + (x + col), HEART_R, HEART_G, HEART_B)
      end
      col += 1
    end
    row += 1
  end
  led.show
end

# ================================================================
# Main loop
# ================================================================
x = (GRID_W - HEART_W) / 2
y = (GRID_H - HEART_H) / 2

player = MusicPlayer.new(buzzer, MEGALOVANIA_SAW_DATA)

# Per-direction cooldown counters. 0 means "fire on next poll", so a
# fresh press after release moves immediately, then auto-repeats at
# CONTROL_REPEAT_MS while held.
ready_l = 0
ready_r = 0
ready_u = 0
ready_d = 0

draw_heart(led, x, y)
last_ms = Machine.board_millis

loop do
  now_ms = Machine.board_millis
  dt     = now_ms - last_ms
  last_ms = now_ms

  player.tick(dt)

  if btn_left.low?
    ready_l -= dt
    if ready_l <= 0
      x -= 1 if x > 0
      ready_l = CONTROL_REPEAT_MS
    end
  else
    ready_l = 0
  end

  if btn_right.low?
    ready_r -= dt
    if ready_r <= 0
      x += 1 if x < GRID_W - HEART_W
      ready_r = CONTROL_REPEAT_MS
    end
  else
    ready_r = 0
  end

  if btn_up.low?
    ready_u -= dt
    if ready_u <= 0
      y -= 1 if y > 0
      ready_u = CONTROL_REPEAT_MS
    end
  else
    ready_u = 0
  end

  if btn_down.low?
    ready_d -= dt
    if ready_d <= 0
      y += 1 if y < GRID_H - HEART_H
      ready_d = CONTROL_REPEAT_MS
    end
  else
    ready_d = 0
  end

  draw_heart(led, x, y)
end
