# Board43 App: Undertale Battle (v3)
#
# Dodge-box prototype: a red downward-triangle "SOUL" moves with the
# four buttons while a short melody loops on the piezo. Song data is
# pre-compiled to packed bytes by my-apps/songs/build.py; this file
# never parses note names at runtime.
#
#   SW3: Left
#   SW4: Up
#   SW5: Down
#   SW6: Right
#
# Features: Switches (GPIO) + WS2812 16x16 matrix + Buzzer (PWM)

require 'ws2812-plus'
require 'gpio'
require 'pwm'

# ================================================================
# MusicPlayer — byte-decoding monophonic song player
# ================================================================
#
# Song data is a packed byte stream with 4 bytes per event:
#   bytes 0-1: frequency Hz (little-endian, 0 = rest)
#   bytes 2-3: duration ms  (little-endian)
# Articulation gaps between same-pitch repeats are baked in already,
# so #tick does no parsing and no table lookups.
#
# Callers pass a pre-converted Array<Integer> (obtained once at boot
# via `SOME_SONG_DATA.bytes`). The player never allocates during
# playback or track switching — `#play` just swaps the reference.
#
#   player = MusicPlayer.new(buzzer)
#   player.play(SONGS[:megalovania])
#   loop do
#     player.tick(dt)
#     # ... draw your frame ...
#   end
class MusicPlayer
  def initialize(buzzer)
    @buzzer    = buzzer
    @bytes     = nil
    @count     = 0
    @cursor    = 0
    @remaining = 0
  end

  # Swap to a different song. `song_bytes` is a pre-converted int
  # array; no allocation happens here. Safe to call mid-playback.
  def play(song_bytes)
    @bytes     = song_bytes
    @count     = song_bytes.length / 4
    @cursor    = 0
    @remaining = 0
  end

  # Advance playback by elapsed_ms. Common-case cost: one subtract +
  # one compare. Uses a while loop so multiple short events that fit
  # inside a single tick don't get dropped.
  def tick(elapsed_ms)
    return unless @bytes
    @remaining -= elapsed_ms
    while @remaining <= 0
      i = @cursor * 4
      freq = @bytes[i] | (@bytes[i + 1] << 8)
      dur  = @bytes[i + 2] | (@bytes[i + 3] << 8)
      @buzzer.frequency(freq)
      @remaining += dur
      @cursor += 1
      @cursor = 0 if @cursor >= @count
    end
  end

  def stop
    @buzzer.frequency(0)
  end
end

# ================================================================
# Song data — generated by `uv run my-apps/songs/build.py <this-file>`.
# Add another song by dropping `<name>.song` into my-apps/songs/ and
# inserting another `# BEGIN SONG: <name>` / `# END SONG` pair below.
# ================================================================
# BEGIN SONG: megalovania
# 531 notes -> 547 events, 2188 bytes
MEGALOVANIA_DATA = \
  "\x26\x01\x73\x00\x00\x00\x0a\x00\x26\x01\x7d\x00\x4b\x02\x7d\x00\x00\x00\x7d\x00\xb8\x01\x7d\x00\x00\x00\xfa\x00\x9f\x01\x7d\x00" \
  "\x00\x00\x7d\x00\x88\x01\x7d\x00\x00\x00\x7d\x00\x5d\x01\xfa\x00\x26\x01\x7d\x00\x5d\x01\x7d\x00\x88\x01\x7d\x00\x06\x01\x73\x00" \
  "\x00\x00\x0a\x00\x06\x01\x7d\x00\x4b\x02\x7d\x00\x00\x00\x7d\x00\xb8\x01\x7d\x00\x00\x00\xfa\x00\x9f\x01\x7d\x00\x00\x00\x7d\x00" \
  "\x88\x01\x7d\x00\x00\x00\x7d\x00\x5d\x01\xfa\x00\x26\x01\x7d\x00\x5d\x01\x7d\x00\x88\x01\x7d\x00\xf7\x00\x73\x00\x00\x00\x0a\x00" \
  "\xf7\x00\x7d\x00\x4b\x02\x7d\x00\x00\x00\x7d\x00\xb8\x01\x7d\x00\x00\x00\xfa\x00\x9f\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\x7d\x00" \
  "\x00\x00\x7d\x00\x5d\x01\xfa\x00\x26\x01\x7d\x00\x5d\x01\x7d\x00\x88\x01\x7d\x00\xe9\x00\x73\x00\x00\x00\x0a\x00\xe9\x00\x7d\x00" \
  "\x4b\x02\x7d\x00\x00\x00\x7d\x00\xb8\x01\x7d\x00\x00\x00\xfa\x00\x9f\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\x7d\x00\x00\x00\x7d\x00" \
  "\x5d\x01\xfa\x00\x26\x01\x7d\x00\x5d\x01\x7d\x00\x88\x01\x7d\x00\x26\x01\x73\x00\x00\x00\x0a\x00\x26\x01\x7d\x00\x4b\x02\x7d\x00" \
  "\x00\x00\x7d\x00\xb8\x01\x7d\x00\x00\x00\xfa\x00\x9f\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\x7d\x00\x00\x00\x7d\x00\x5d\x01\xfa\x00" \
  "\x26\x01\x7d\x00\x5d\x01\x7d\x00\x88\x01\x7d\x00\x06\x01\x73\x00\x00\x00\x0a\x00\x06\x01\x7d\x00\x4b\x02\x7d\x00\x00\x00\x7d\x00" \
  "\xb8\x01\x7d\x00\x00\x00\xfa\x00\x9f\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\x7d\x00\x00\x00\x7d\x00\x5d\x01\xfa\x00\x26\x01\x7d\x00" \
  "\x5d\x01\x7d\x00\x88\x01\x7d\x00\xf7\x00\x73\x00\x00\x00\x0a\x00\xf7\x00\x7d\x00\x4b\x02\x7d\x00\x00\x00\x7d\x00\xb8\x01\x7d\x00" \
  "\x00\x00\xfa\x00\x9f\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\x7d\x00\x00\x00\x7d\x00\x5d\x01\xfa\x00\x26\x01\x7d\x00\x5d\x01\x7d\x00" \
  "\x88\x01\x7d\x00\xe9\x00\x73\x00\x00\x00\x0a\x00\xe9\x00\x7d\x00\x4b\x02\x7d\x00\x00\x00\x7d\x00\xb8\x01\x7d\x00\x00\x00\xfa\x00" \
  "\x9f\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\x7d\x00\x00\x00\x7d\x00\x5d\x01\xfa\x00\x26\x01\x7d\x00\x5d\x01\x7d\x00\x88\x01\x7d\x00" \
  "\x26\x01\x73\x00\x00\x00\x0a\x00\x26\x01\x7d\x00\x4b\x02\x7d\x00\x00\x00\x7d\x00\xb8\x01\x7d\x00\x00\x00\xfa\x00\x9f\x01\x7d\x00" \
  "\x00\x00\x7d\x00\x88\x01\x7d\x00\x00\x00\x7d\x00\x5d\x01\xfa\x00\x26\x01\x7d\x00\x5d\x01\x7d\x00\x88\x01\x7d\x00\x06\x01\x73\x00" \
  "\x00\x00\x0a\x00\x06\x01\x7d\x00\x4b\x02\x7d\x00\x00\x00\x7d\x00\xb8\x01\x7d\x00\x00\x00\xfa\x00\x9f\x01\x7d\x00\x00\x00\x7d\x00" \
  "\x88\x01\x7d\x00\x00\x00\x7d\x00\x5d\x01\xfa\x00\x26\x01\x7d\x00\x5d\x01\x7d\x00\x88\x01\x7d\x00\xf7\x00\x73\x00\x00\x00\x0a\x00" \
  "\xf7\x00\x7d\x00\x4b\x02\x7d\x00\x00\x00\x7d\x00\xb8\x01\x7d\x00\x00\x00\xfa\x00\x9f\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\x7d\x00" \
  "\x00\x00\x7d\x00\x5d\x01\xfa\x00\x26\x01\x7d\x00\x5d\x01\x7d\x00\x88\x01\x7d\x00\xe9\x00\x73\x00\x00\x00\x0a\x00\xe9\x00\x7d\x00" \
  "\x4b\x02\x7d\x00\x00\x00\x7d\x00\xb8\x01\x7d\x00\x00\x00\xfa\x00\x9f\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\x7d\x00\x00\x00\x7d\x00" \
  "\x5d\x01\xfa\x00\x26\x01\x7d\x00\x5d\x01\x7d\x00\x88\x01\x7d\x00\x26\x01\x73\x00\x00\x00\x0a\x00\x26\x01\x7d\x00\x4b\x02\x7d\x00" \
  "\x00\x00\x7d\x00\xb8\x01\x7d\x00\x00\x00\xfa\x00\x9f\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\x7d\x00\x00\x00\x7d\x00\x5d\x01\xfa\x00" \
  "\x26\x01\x7d\x00\x5d\x01\x7d\x00\x88\x01\x7d\x00\x06\x01\x73\x00\x00\x00\x0a\x00\x06\x01\x7d\x00\x4b\x02\x7d\x00\x00\x00\x7d\x00" \
  "\xb8\x01\x7d\x00\x00\x00\xfa\x00\x9f\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\x7d\x00\x00\x00\x7d\x00\x5d\x01\xfa\x00\x26\x01\x7d\x00" \
  "\x5d\x01\x7d\x00\x88\x01\x7d\x00\xf7\x00\x73\x00\x00\x00\x0a\x00\xf7\x00\x7d\x00\x4b\x02\x7d\x00\x00\x00\x7d\x00\xb8\x01\x7d\x00" \
  "\x00\x00\xfa\x00\x9f\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\x7d\x00\x00\x00\x7d\x00\x5d\x01\xfa\x00\x26\x01\x7d\x00\x5d\x01\x7d\x00" \
  "\x88\x01\x7d\x00\xe9\x00\x73\x00\x00\x00\x0a\x00\xe9\x00\x7d\x00\x4b\x02\x7d\x00\x00\x00\x7d\x00\xb8\x01\x7d\x00\x00\x00\xfa\x00" \
  "\x9f\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\x7d\x00\x00\x00\x7d\x00\x5d\x01\xfa\x00\x26\x01\x7d\x00\x5d\x01\x7d\x00\x88\x01\x7d\x00" \
  "\xba\x02\x5e\x00\x00\x00\x7d\x00\xba\x02\x5e\x00\x00\x00\x3e\x00\xba\x02\x5e\x00\x00\x00\x9c\x00\x93\x02\x7d\x00\x00\x00\x7d\x00" \
  "\xba\x02\x5e\x00\x00\x00\x9c\x00\x4b\x02\x5e\x00\x00\x00\x9c\x00\x4b\x02\x32\x02\x00\x00\x3e\x00\xba\x02\x3e\x00\x00\x00\xbc\x00" \
  "\xba\x02\x3e\x00\x00\x00\x3e\x00\xba\x02\x3e\x00\x00\x00\xbc\x00\x10\x03\x3e\x00\x00\x00\xbc\x00\x3f\x03\xfa\x00\x10\x03\x1f\x00" \
  "\xba\x02\x1f\x00\x3f\x03\x1f\x00\x10\x03\x1f\x00\xba\x02\x3e\x00\x00\x00\x3e\x00\x4b\x02\x3e\x00\x00\x00\x3e\x00\xba\x02\x7d\x00" \
  "\x10\x03\x3e\x00\x00\x00\x38\x01\xba\x02\x5e\x00\x00\x00\x9c\x00\xba\x02\x5e\x00\x00\x00\x1f\x00\xba\x02\x5e\x00\x00\x00\x9c\x00" \
  "\x10\x03\x5e\x00\x00\x00\x9c\x00\x3f\x03\x5e\x00\x00\x00\x9c\x00\x70\x03\x5e\x00\x00\x00\x9c\x00\x17\x04\x5e\x00\x00\x00\x9c\x00" \
  "\x70\x03\x77\x01\x97\x04\x5e\x00\x00\x00\x7d\x00\x97\x04\x5e\x00\x00\x00\xbc\x00\x97\x04\x5e\x00\x00\x00\x1f\x00\x70\x03\x5e\x00" \
  "\x00\x00\x1f\x00\x97\x04\x5e\x00\x00\x00\x1f\x00\x17\x04\x65\x04\x70\x03\x5e\x00\x00\x00\x7d\x00\x70\x03\x5e\x00\x00\x00\x3e\x00" \
  "\x70\x03\x5e\x00\x00\x00\x9c\x00\x70\x03\x5e\x00\x00\x00\x9c\x00\x70\x03\x5e\x00\x00\x00\xa1\x00\x10\x03\x5e\x00\x00\x00\x9c\x00" \
  "\x10\x03\x32\x02\x00\x00\x39\x00\x70\x03\x5e\x00\x00\x00\x9c\x00\x70\x03\x5e\x00\x00\x00\x1f\x00\x70\x03\x5e\x00\x00\x00\x9c\x00" \
  "\x70\x03\x5e\x00\x00\x00\x9c\x00\x10\x03\x5e\x00\x00\x00\x9c\x00\x70\x03\x5e\x00\x00\x00\x9c\x00\x97\x04\x5e\x00\x00\x00\x9c\x00" \
  "\x70\x03\x5e\x00\x00\x00\x1f\x00\x10\x03\xfa\x00\x97\x04\x5e\x00\x00\x00\x9c\x00\x70\x03\x5e\x00\x00\x00\x9c\x00\x10\x03\x5e\x00" \
  "\x00\x00\x9c\x00\xba\x02\x5e\x00\x00\x00\x9c\x00\x17\x04\x5e\x00\x00\x00\x9c\x00\x10\x03\x5e\x00\x00\x00\x9c\x00\xba\x02\x5e\x00" \
  "\x00\x00\x9c\x00\x93\x02\x5e\x00\x00\x00\x9c\x00\xd2\x01\x5e\x00\x00\x00\x9c\x00\x4b\x02\x5e\x00\x00\x00\x1f\x00\x93\x02\x5e\x00" \
  "\x00\x00\xbc\x00\xba\x02\x5e\x00\x00\x00\x7d\x00\x17\x04\x2c\x04\x00\x00\xe8\x03\x5d\x01\x39\x00\x00\x00\x44\x00\x26\x01\x39\x00" \
  "\x00\x00\x44\x00\x5d\x01\x39\x00\x00\x00\x44\x00\x88\x01\x39\x00\x00\x00\x44\x00\x9f\x01\x39\x00\x00\x00\x49\x00\x88\x01\x39\x00" \
  "\x00\x00\x3e\x00\x5d\x01\x39\x00\x00\x00\x44\x00\x26\x01\x39\x00\x00\x00\x44\x00\x9f\x01\x1f\x00\x00\x00\x1f\x00\x88\x01\x1f\x00" \
  "\x00\x00\x1f\x00\x5d\x01\x1f\x00\x00\x00\x1f\x00\x26\x01\x1f\x00\x00\x00\x1f\x00\x5d\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\xa4\x04" \
  "\x9f\x01\x7d\x00\x00\x00\x3e\x00\xb8\x01\x3e\x00\x00\x00\x3e\x00\x0b\x02\x7d\x00\x00\x00\x7d\x00\xb8\x01\x3e\x00\x00\x00\x3e\x00" \
  "\x9f\x01\x3e\x00\x00\x00\x3e\x00\x88\x01\x3e\x00\x00\x00\x3e\x00\x5d\x01\x3e\x00\x00\x00\x3e\x00\x26\x01\x3e\x00\x00\x00\x3e\x00" \
  "\x4a\x01\x7d\x00\x5d\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\x7d\x00\x00\x00\x7d\x00\xb8\x01\x7d\x00\x00\x00\x7d\x00\x0b\x02\x7d\x00" \
  "\x00\x00\x7d\x00\x2a\x02\xfa\x00\x9f\x01\x7d\x00\x00\x00\x7d\x00\x9f\x01\x7d\x00\x88\x01\x7d\x00\x5d\x01\x7d\x00\x88\x01\x65\x04" \
  "\xaf\x00\x7d\x00\x00\x00\x7d\x00\xc4\x00\x7d\x00\x00\x00\x7d\x00\xdc\x00\x7d\x00\x00\x00\x7d\x00\x5d\x01\x7d\x00\x00\x00\x7d\x00" \
  "\x4a\x01\xf4\x01\x26\x01\xf4\x01\x4a\x01\xf4\x01\x5d\x01\xf4\x01\x88\x01\xf4\x01\x4a\x01\xf4\x01\xb8\x01\x6b\x03\x00\x00\x7d\x00" \
  "\xb8\x01\x3e\x00\x00\x00\x3e\x00\x9f\x01\x3e\x00\x00\x00\x3e\x00\x88\x01\x3e\x00\x00\x00\x3e\x00\x72\x01\x3e\x00\x00\x00\x3e\x00" \
  "\x5d\x01\x3e\x00\x00\x00\x3e\x00\x4a\x01\x3e\x00\x00\x00\x3e\x00\x37\x01\x3e\x00\x00\x00\x3e\x00\x26\x01\x3e\x00\x00\x00\x3e\x00" \
  "\x15\x01\x6b\x03\x00\x00\x7d\x00\x37\x01\xe8\x03\x00\x00\xe8\x03\x5d\x01\x39\x00\x00\x00\x44\x00\x26\x01\x39\x00\x00\x00\x44\x00" \
  "\x5d\x01\x39\x00\x00\x00\x44\x00\x88\x01\x39\x00\x00\x00\x44\x00\x9f\x01\x39\x00\x00\x00\x49\x00\x88\x01\x39\x00\x00\x00\x3e\x00" \
  "\x5d\x01\x39\x00\x00\x00\x44\x00\x26\x01\x39\x00\x00\x00\x44\x00\x9f\x01\x1f\x00\x00\x00\x1f\x00\x88\x01\x1f\x00\x00\x00\x1f\x00" \
  "\x5d\x01\x1f\x00\x00\x00\x1f\x00\x26\x01\x1f\x00\x00\x00\x1f\x00\x5d\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\xa4\x04\x9f\x01\x7d\x00" \
  "\x00\x00\x3e\x00\xb8\x01\x3e\x00\x00\x00\x3e\x00\x0b\x02\x7d\x00\x00\x00\x7d\x00\xb8\x01\x3e\x00\x00\x00\x3e\x00\x9f\x01\x3e\x00" \
  "\x00\x00\x3e\x00\x88\x01\x3e\x00\x00\x00\x3e\x00\x5d\x01\x3e\x00\x00\x00\x3e\x00\x26\x01\x3e\x00\x00\x00\x3e\x00\x4a\x01\x7d\x00" \
  "\x5d\x01\x7d\x00\x00\x00\x7d\x00\x88\x01\x7d\x00\x00\x00\x7d\x00\xb8\x01\x7d\x00\x00\x00\x7d\x00\x0b\x02\x7d\x00\x00\x00\x7d\x00" \
  "\x2a\x02\xfa\x00\x9f\x01\x7d\x00\x00\x00\x7d\x00\x9f\x01\x7d\x00\x88\x01\x7d\x00\x5d\x01\x7d\x00\x88\x01\x65\x04\xaf\x00\x7d\x00" \
  "\x00\x00\x7d\x00\xc4\x00\x7d\x00\x00\x00\x7d\x00\xdc\x00\x7d\x00\x00\x00\x7d\x00\x5d\x01\x7d\x00\x00\x00\x7d\x00\x4a\x01\xf4\x01" \
  "\x26\x01\xf4\x01\x4a\x01\xf4\x01\x5d\x01\xf4\x01\x88\x01\xf4\x01\x4a\x01\xf4\x01\xb8\x01\x6b\x03\x00\x00\x7d\x00\xb8\x01\x3e\x00" \
  "\x00\x00\x3e\x00\x9f\x01\x3e\x00\x00\x00\x3e\x00\x88\x01\x3e\x00\x00\x00\x3e\x00\x72\x01\x3e\x00\x00\x00\x3e\x00\x5d\x01\x3e\x00" \
  "\x00\x00\x3e\x00\x4a\x01\x3e\x00\x00\x00\x3e\x00\x37\x01\x3e\x00\x00\x00\x3e\x00\x26\x01\x3e\x00\x00\x00\x3e\x00\x15\x01\x6b\x03" \
  "\x00\x00\x7d\x00\x37\x01\xe8\x03\x00\x00\xf4\x01"
# END SONG
# BEGIN SONG: determination
# 162 notes -> 162 events, 648 bytes
DETERMINATION_DATA = \
  "\x72\x01\x05\x01\x5d\x01\x05\x01\x37\x01\x05\x01\x15\x01\x05\x01\x37\x01\x05\x01\xe9\x00\x05\x01\x06\x01\x05\x01\x00\x00\x05\x01" \
  "\xd0\x00\x05\x01\x00\x00\x05\x01\x37\x01\x05\x01\x5d\x01\x05\x01\x72\x01\x05\x01\x00\x00\x05\x01\x9f\x01\x05\x01\x00\x00\x05\x01" \
  "\x2a\x02\x05\x01\x00\x00\x05\x01\xd2\x01\x13\x04\x00\x00\x0a\x02\x72\x01\x05\x01\x5d\x01\x05\x01\x37\x01\x05\x01\x15\x01\x05\x01" \
  "\x37\x01\x05\x01\xe9\x00\x05\x01\x06\x01\x05\x01\x00\x00\x05\x01\xd0\x00\x05\x01\x00\x00\x05\x01\x9c\x00\x05\x01\xaf\x00\x05\x01" \
  "\xb9\x00\x05\x01\x00\x00\x05\x01\xaf\x00\x05\x01\x00\x00\x05\x01\x8b\x00\x05\x01\x00\x00\x05\x01\x9c\x00\x13\x04\x00\x00\x0a\x02" \
  "\x72\x01\x05\x01\x5d\x01\x05\x01\x37\x01\x05\x01\x15\x01\x05\x01\x37\x01\x05\x01\xe9\x00\x05\x01\x06\x01\x05\x01\x00\x00\x05\x01" \
  "\xd0\x00\x05\x01\x00\x00\x05\x01\x37\x01\x05\x01\x5d\x01\x05\x01\x72\x01\x05\x01\x00\x00\x05\x01\x9f\x01\x05\x01\x00\x00\x05\x01" \
  "\x2a\x02\x05\x01\x00\x00\x05\x01\xd2\x01\x13\x04\x00\x00\x0a\x02\x72\x01\x05\x01\x5d\x01\x05\x01\x37\x01\x05\x01\x15\x01\x05\x01" \
  "\x37\x01\x05\x01\xe9\x00\x05\x01\x06\x01\x05\x01\x00\x00\x05\x01\xd0\x00\x05\x01\x00\x00\x05\x01\x9c\x00\x05\x01\xaf\x00\x05\x01" \
  "\xb9\x00\x05\x01\x00\x00\x05\x01\xaf\x00\x05\x01\x00\x00\x05\x01\x8b\x00\x05\x01\x00\x00\x05\x01\x9c\x00\x13\x04\x00\x00\x0a\x02" \
  "\x9f\x01\x05\x01\x72\x01\x05\x01\x4a\x01\x05\x01\x37\x01\x05\x01\x15\x01\x05\x01\x4a\x01\x05\x01\x37\x01\x05\x01\x00\x00\x05\x01" \
  "\xe9\x00\x05\x01\x00\x00\x05\x01\xe9\x00\x05\x01\x37\x01\x05\x01\x9f\x01\x05\x01\x72\x01\x05\x01\x4a\x01\x05\x01\x37\x01\x05\x01" \
  "\x15\x01\x05\x01\x4a\x01\x05\x01\x37\x01\x0f\x03\x00\x00\x05\x01\x9c\x00\x05\x01\xd0\x00\x05\x01\x15\x01\x05\x01\x06\x01\x05\x01" \
  "\xe9\x00\x05\x01\xd0\x00\x05\x01\xe9\x00\x05\x01\x06\x01\x05\x01\xe9\x00\x05\x01\x00\x00\x05\x01\x9c\x00\x05\x01\x00\x00\x05\x01" \
  "\x75\x00\x05\x01\x8b\x00\x05\x01\x9c\x00\x05\x01\x00\x00\x05\x01\xf7\x00\x05\x01\x00\x00\x05\x01\x37\x01\x0a\x02\x26\x01\x13\x04" \
  "\x00\x00\x0a\x02\x9f\x01\x05\x01\x72\x01\x05\x01\x4a\x01\x05\x01\x37\x01\x05\x01\x15\x01\x05\x01\x4a\x01\x05\x01\x37\x01\x05\x01" \
  "\x00\x00\x05\x01\xe9\x00\x05\x01\x00\x00\x05\x01\xe9\x00\x05\x01\x37\x01\x05\x01\x9f\x01\x05\x01\x72\x01\x05\x01\x4a\x01\x05\x01" \
  "\x37\x01\x05\x01\x15\x01\x05\x01\x4a\x01\x05\x01\x37\x01\x0f\x03\x00\x00\x05\x01\x9c\x00\x05\x01\xd0\x00\x05\x01\x15\x01\x05\x01" \
  "\x06\x01\x05\x01\xe9\x00\x05\x01\xd0\x00\x05\x01\xe9\x00\x05\x01\x06\x01\x05\x01\xe9\x00\x05\x01\x00\x00\x05\x01\x9c\x00\x05\x01" \
  "\x00\x00\x05\x01\x75\x00\x05\x01\x8b\x00\x05\x01\x9c\x00\x05\x01\x00\x00\x05\x01\x8b\x00\x05\x01\x00\x00\x05\x01\x68\x00\x05\x01" \
  "\x00\x00\x05\x01\x75\x00\x13\x04"
# END SONG

# ================================================================
# Shared display geometry
# ================================================================
# Only GRID_W / GRID_H live at the top level — both scenes address
# the same physical matrix. Everything else (sprites, colors, gameplay
# timing, song data) lives inside the scene class that owns it.
GRID_W = 16
GRID_H = 16

# ================================================================
# Hardware
# ================================================================
led       = WS2812.new(pin: Board43::GPIO_LEDOUT, num: 256)
btn_left  = GPIO.new(Board43::GPIO_SW3, GPIO::IN | GPIO::PULL_UP)
btn_up    = GPIO.new(Board43::GPIO_SW4, GPIO::IN | GPIO::PULL_UP)
btn_down  = GPIO.new(Board43::GPIO_SW5, GPIO::IN | GPIO::PULL_UP)
btn_right = GPIO.new(Board43::GPIO_SW6, GPIO::IN | GPIO::PULL_UP)
buzzer    = PWM.new(Board43::GPIO_BUZZER, frequency: 0, duty: 40)

# ================================================================
# Scenes
# ================================================================
#
# Each scene is a small object with #tick(dt) that advances the
# scene by one frame and returns either a Symbol (to request a
# transition to that scene) or nil (to stay). Scene state lives as
# @ivars so nothing has to be reconstructed per frame.
#
# The outer loop at the bottom of this file owns the dt clock and
# the scene dispatch. Scenes never loop on their own.

# Title scene: silent, Sans sprite scrolls right-to-left with a
# full-screen gap between repeats. SW6 press edge → :main.
class TitleScene
  # Sprite is 17 wide × 15 tall (one column wider than the matrix),
  # pre-converted to byte rows so the draw loop is pure index
  # lookup. Glyph codes: '#' = white, 'K' = dark grey, '.' = off.
  SANS_SPRITE = [
    "....KKKKKKKKK....",
    "..KK#########KK..",
    ".K#############K.",
    ".K#############K.",
    "K###############K",
    "K##########KKK##K",
    "K##########KKK##K",
    "K##KKK##K##KKK##K",
    ".K#####KKK#####K.",
    "KK#K#########K#KK",
    "K##KKKKKKKKKKK##K",
    "K###K#K#K#K#K###K",
    ".KK##KKKKKKK##KK.",
    "...KK#######KK...",
    ".....KKKKKKK.....",
  ]
  SANS_BYTES  = SANS_SPRITE.map { |row| row.bytes }
  SANS_W      = 17
  SANS_H      = 15
  SANS_Y      = 0            # top-align; bottom row stays blank
  SANS_GAP    = GRID_W       # one full blank screen between repeats
  SANS_PERIOD = SANS_W + SANS_GAP

  # Byte values of the sprite glyphs (avoids char-compare at runtime).
  C_WHITE = 35  # '#'
  C_GREY  = 75  # 'K'

  # Render colors. White pixels render as actual white; "black"
  # pixels render as a very dim blue that just barely lights the LED
  # so the silhouette reads against the (fully off) transparent
  # pixels.
  WHITE_R = 180
  WHITE_G = 180
  WHITE_B = 180
  GREY_R  = 0
  GREY_G  = 0
  GREY_B  = 40

  SCROLL_MS_PER_PX = 140  # sprite advances one column every 140 ms

  def initialize(led, btn_right, buzzer)
    @led       = led
    @btn_right = btn_right
    buzzer.frequency(0)

    @scroll_x     = 0
    @scroll_accum = 0

    # Seed the edge detector with the current state so a button
    # already held at boot doesn't instantly skip the title.
    @prev_down = btn_right.low?
  end

  def tick(dt)
    @scroll_accum += dt
    while @scroll_accum >= SCROLL_MS_PER_PX
      @scroll_accum -= SCROLL_MS_PER_PX
      @scroll_x = (@scroll_x + 1) % SANS_PERIOD
    end
    render

    now_down = @btn_right.low?
    fired = now_down && !@prev_down
    @prev_down = now_down
    fired ? :main : nil
  end

  # Render the scrolling sprite. We iterate screen columns rather
  # than sprite columns so blank columns between repeats cost
  # nothing. `@scroll_x` is the current left-edge offset into the
  # infinite SANS_PERIOD-wide tape (sprite followed by one full
  # blank screen, repeating).
  def render
    @led.fill(0, 0, 0)
    col = 0
    while col < GRID_W
      sprite_col = (col + @scroll_x) % SANS_PERIOD
      if sprite_col < SANS_W
        row = 0
        while row < SANS_H
          code = SANS_BYTES[row][sprite_col]
          idx  = (SANS_Y + row) * GRID_W + col
          if code == C_WHITE
            @led.set_rgb(idx, WHITE_R, WHITE_G, WHITE_B)
          elsif code == C_GREY
            @led.set_rgb(idx, GREY_R, GREY_G, GREY_B)
          end
          row += 1
        end
      end
      col += 1
    end
    @led.show
  end
end

# Main scene (prototype): SOUL moves under the four-button control,
# megalovania loops on the buzzer, Left+Right chord toggles tracks.
#
# Input model:
#   Each direction has a `@ready_X` countdown in ms. When a button
#   is released we reset it to 0 so the next fresh press fires on
#   the very next poll (zero perceived latency). While held, `dt`
#   drains it; when it reaches 0, we step one cell and reload to
#   CONTROL_REPEAT_MS. This gives snap-to-first-press + smooth
#   auto-repeat without edge detection state.
#
# Debug track toggle:
#   Left+Right pressed together (a physically-impossible movement
#   combo) advances TRACK_ORDER by one. Edge-detected via
#   `@chord_held` so the toggle fires once per chord press, not
#   once per frame. Movement for L and R is suppressed while the
#   chord is held.
class MainScene
  # 3x2 "red T" downward triangle — compact, leaves room for attacks.
  HEART_SPRITE = ['###', '.#.']
  HEART_W = 3
  HEART_H = 2

  # Heart color is driven by mode:
  #   :red  — free movement (classic Undertale).
  #   :blue — gravity platformer; vertical input is "jump only".
  HEART_RED_R  = 200
  HEART_RED_G  = 0
  HEART_RED_B  = 0
  HEART_BLUE_R = 0
  HEART_BLUE_G = 0
  HEART_BLUE_B = 200

  # HP bar occupies the bottom row of the matrix. Heart movement is
  # clamped to PLAY_H so the heart can't paint over it.
  HP_ROW = GRID_H - 1
  HP_MAX = GRID_W
  HP_R   = 200
  HP_G   = 200
  HP_B   = 0

  PLAY_H = GRID_H - 1   # playfield excludes the HP row

  CONTROL_REPEAT_MS = 96   # step every ~96 ms while a button is held

  # --- Blue-mode physics --------------------------------------------
  #
  # Vertical position is integrated as a Float (rows; @y_f) and only
  # truncated to an integer (@y) for rendering.
  #
  # Variable-height jump: holding Up lets the upward velocity decay
  # naturally under gravity; releasing Up while still ascending
  # zeroes @vy on the spot, so gravity takes over immediately. Short
  # tap → short hop, full hold → max-height jump. Once released (or
  # once the apex is reached) the heart is committed to falling all
  # the way back to the floor — re-pressing Up mid-air is a no-op
  # because the edge-detected jump trigger only fires while grounded.
  #
  # Tuning: a full-hold jump's kinematic peak slightly overshoots 12
  # rows (= 3/4 of the 16-row screen), and the absolute clamp at
  # JUMP_PEAK_Y catches the rest. Time to peak ≈ 600 ms, fall back
  # ≈ 775 ms, total air time ≈ 1.4 s.
  #
  #   peak_height = JUMP_V0² / (2 * GRAVITY) = 0.032² / 0.00008 ≈ 12.8
  #
  # Integration is semi-implicit Euler (`@vy += g*dt; @y += @vy*dt`),
  # which is energy-stable for ballistic motion.
  GRAVITY     = 0.00004          # rows / ms²  (≈ 40 rows/s²)
  JUMP_V0     = 0.032            # rows / ms   (applied as -JUMP_V0)
  GROUND_Y    = PLAY_H - HEART_H # heart's @y when standing on the floor
  JUMP_PEAK_Y = 4                # absolute ceiling for any jump

  # Pre-convert each song's packed byte String to an Array<Integer>
  # exactly once at class-load time. MusicPlayer#play swaps
  # references into this hash, so switching tracks at runtime never
  # allocates. Add a new song by appending to both SONGS and
  # TRACK_ORDER.
  SONGS = {
    megalovania:   MEGALOVANIA_DATA.bytes,
    determination: DETERMINATION_DATA.bytes,
  }
  TRACK_ORDER = [:megalovania, :determination]

  def initialize(led, btn_left, btn_up, btn_down, btn_right, buzzer)
    @led       = led
    @btn_left  = btn_left
    @btn_up    = btn_up
    @btn_down  = btn_down
    @btn_right = btn_right

    @player   = MusicPlayer.new(buzzer)
    @track_ix = 0
    @player.play(SONGS[TRACK_ORDER[@track_ix]])

    # Default to blue mode so the gravity prototype is what comes up
    # on boot. Switch this to :red to test the free-movement variant.
    @mode = :blue

    @x   = (GRID_W - HEART_W) / 2
    @y_f = GROUND_Y.to_f   # float source of truth; @y is derived
    @y   = GROUND_Y
    @vy  = 0.0             # rows / ms  (negative = upward)
    @hp  = HP_MAX

    @ready_l    = 0
    @ready_r    = 0
    @ready_u    = 0
    @ready_d    = 0
    @chord_held = false
    @up_prev    = false    # edge-detect for jump

    render
  end

  def tick(dt)
    @player.tick(dt)

    tick_horizontal(dt)
    if @mode == :blue
      tick_vertical_blue(dt)
    else
      tick_vertical_red(dt)
    end

    render
    nil
  end

  # Horizontal movement is shared by both modes. Auto-repeat steps
  # one cell per CONTROL_REPEAT_MS while a button is held; releasing
  # resets the counter so the next press fires on the very next poll.
  # Left+Right held together cycles the music track for debug.
  def tick_horizontal(dt)
    l_down = @btn_left.low?
    r_down = @btn_right.low?

    if l_down && r_down
      unless @chord_held
        @track_ix = (@track_ix + 1) % TRACK_ORDER.length
        @player.play(SONGS[TRACK_ORDER[@track_ix]])
        @chord_held = true
      end
      @ready_l = 0
      @ready_r = 0
      return
    end
    @chord_held = false

    if l_down
      @ready_l -= dt
      if @ready_l <= 0
        @x -= 1 if @x > 0
        @ready_l = CONTROL_REPEAT_MS
      end
    else
      @ready_l = 0
    end

    if r_down
      @ready_r -= dt
      if @ready_r <= 0
        @x += 1 if @x < GRID_W - HEART_W
        @ready_r = CONTROL_REPEAT_MS
      end
    else
      @ready_r = 0
    end
  end

  # Red mode: free vertical movement with the same auto-repeat model
  # as horizontal. Keeps @y_f in sync so a future mode switch into
  # blue starts from a sane integer position with zero velocity.
  def tick_vertical_red(dt)
    if @btn_up.low?
      @ready_u -= dt
      if @ready_u <= 0
        @y -= 1 if @y > 0
        @ready_u = CONTROL_REPEAT_MS
      end
    else
      @ready_u = 0
    end

    if @btn_down.low?
      @ready_d -= dt
      if @ready_d <= 0
        @y += 1 if @y < PLAY_H - HEART_H
        @ready_d = CONTROL_REPEAT_MS
      end
    else
      @ready_d = 0
    end

    @y_f = @y.to_f
    @vy  = 0.0
  end

  # Blue mode: gravity is always pulling down; Up edge-press while
  # grounded launches a jump. No double jump, no fast-fall — a single
  # ballistic arc that's clamped to JUMP_PEAK_Y (3/4 screen) at the
  # top and GROUND_Y at the bottom.
  def tick_vertical_blue(dt)
    up_down  = @btn_up.low?
    grounded = @y_f >= GROUND_Y

    # Edge-press while grounded launches a fresh jump.
    if up_down && !@up_prev && grounded
      @vy = -JUMP_V0
    end
    @up_prev = up_down

    # Variable jump height: releasing Up while still ascending kills
    # the upward velocity. Gravity then takes over and the heart
    # falls to the ground — it cannot re-engage the jump until it
    # lands (the grounded check above guards re-presses in air).
    if !up_down && @vy < 0
      @vy = 0.0
    end

    @vy  += GRAVITY * dt
    @y_f += @vy * dt

    if @y_f >= GROUND_Y
      @y_f = GROUND_Y.to_f
      @vy  = 0.0
    elsif @y_f <= JUMP_PEAK_Y
      # Hard ceiling: stop upward motion so gravity can take over.
      # Don't zero a downward @vy — only kill the upward push.
      @y_f = JUMP_PEAK_Y.to_f
      @vy  = 0.0 if @vy < 0
    end

    @y = @y_f.to_i
  end

  # Full-frame render: clear, HP bar on row HP_ROW, heart sprite.
  # Draw order matters — HP first, then heart on top — so the heart
  # visually takes priority if anything ever overlaps it.
  def render
    @led.fill(0, 0, 0)

    col = 0
    while col < @hp
      @led.set_rgb(HP_ROW * GRID_W + col, HP_R, HP_G, HP_B)
      col += 1
    end

    if @mode == :blue
      hr = HEART_BLUE_R; hg = HEART_BLUE_G; hb = HEART_BLUE_B
    else
      hr = HEART_RED_R;  hg = HEART_RED_G;  hb = HEART_RED_B
    end

    row = 0
    while row < HEART_H
      bytes = HEART_SPRITE[row].bytes
      col = 0
      while col < HEART_W
        if bytes[col] == 35  # '#'
          @led.set_rgb((@y + row) * GRID_W + (@x + col), hr, hg, hb)
        end
        col += 1
      end
      row += 1
    end

    @led.show
  end
end

# ================================================================
# Program — single dt-driven outer loop, scenes dispatched inside.
# ================================================================
#
# Frame cadence is whatever led.show (≈8 ms of WS2812 bit-banging
# for 256 LEDs) plus a few ms of Ruby happens to be on this
# hardware — roughly 10-20 ms. We don't estimate it; we measure
# every frame with Machine.board_millis and feed the real elapsed
# ms (`dt`) to the active scene's #tick.
#
# Contract for any Scene#tick:
#   - All timing state must decrement / accumulate in `dt` units.
#     Never key timing off "N frames"; frame time is variable.
#   - `dt` can spike; #tick must tolerate that. MusicPlayer#tick
#     uses a `while` loop so multiple short events that fit inside
#     one dt don't get dropped.
#   - Return a Symbol to request a scene switch, or nil to stay.
#     Scene construction happens at the frame boundary in the
#     outer loop, so transitions always start a new scene on a
#     fresh frame.
scene = TitleScene.new(led, btn_right, buzzer)
last_ms = Machine.board_millis

loop do
  now_ms  = Machine.board_millis
  dt      = now_ms - last_ms
  last_ms = now_ms

  case scene.tick(dt)
  when :title
    scene = TitleScene.new(led, btn_right, buzzer)
  when :main
    scene = MainScene.new(led, btn_left, btn_up, btn_down, btn_right, buzzer)
  end
end
